### PR TITLE
fix usage of openssl's HMAC library

### PR DESCRIPTION
**Pull request by erankor**
1. must call HMAC_CTX_cleanup to free memory
2. HMAC_CTX_init must be called before using the context

### CODE REVIEW

**Comment by erankor** [comment]
ping

**Comment by refractalize** [comment]
hi @erankor, thanks for the patch. Should we replace `HMAC_Init` with `HMAC_Init_ex`? It looks like `HMAC_Init` has been deprecated.

From https://wiki.openssl.org/index.php/Manual:Hmac(3):

> HMAC_Init_ex() initializes or reuses a HMAC_CTX structure to use the function evp_md and key key. Either can be NULL, in which case the existing one will be reused. HMAC_CTX_init() must have been called before the first use of an HMAC_CTX in this function. N.B. HMAC_Init() had this undocumented behaviour in previous versions of OpenSSL - failure to switch to HMAC_Init_ex() in programs that expect it will cause them to stop working.

**Comment by refractalize** [comment]
by the way, @erankor would you like to maintain this module from now on? I haven't needed this in my work for quite some time and to be honest I'm very rusty on anything to do with OpenSSL.

You already have a fork, if you want I can write a notice to indicate that this fork is deprecated and for people to use yours instead...

**Comment by erankor** [comment]
Hi @refractalize, we can move to HMAC_Init_ex, though I don't think it's a priority at the moment - from what I see, HMAC_Init just calls it with impl=NULL, so unless openssl decides to drop this function, we can leave it as is. 
What was important for me was to fix the leak, it's actually a pretty significant leak (~200+K per request), don't know how no one else noticed it before :)

Regarding your second question, yes, I'd love to maintain this module, I've just created a fork in https://github.com/kaltura/nginx_mod_akamai_g2o (under my company, not my personal user) so it would be great if you would direct people there.

Thanks !

Eran

**Comment by refractalize** [comment]
Cool - ok I'll merge this now and then add a moved notice.

**Pull request merged**
